prog:c.o projet.o
	gcc c.o projet.o -o prog -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer
projet.o:projet.c
	gcc -c projet.c -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer
c.o:c.c
	gcc -c c.c -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer
